-- Seed data pengurus PPDS 1447-1448 H
DELETE FROM ustadz;
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-001', 'M. Khoirul Amini Hasby', '', 'Ketua Umum', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-002', 'Nur M. Said Nawawi', '', 'Ketua I', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-003', 'Bisri Mustofa', '', 'Ketua II', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-004', 'Hasan Baehaki', '', 'Ketua III', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-005', 'Wildan Muhammad', '', 'Sekretaris Umum', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-006', 'M. Chasan Tuqo Asyrofi', '', 'Sekretaris I', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-007', 'M. Syu''aib', '', 'Sekretaris II', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-008', 'Imam Muhyiddin Mansyur', '', 'Sekretaris III', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-009', 'A. Zidan Haqiqi', '', 'Bendahara Umum', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-010', 'Hendri Nurijan', '', 'Bendahara I', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-011', 'Ahmad Sabiq Hanafi', '', 'Seksi Pendidikan & Penerangan (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-012', 'M. Khoirul Huda', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-013', 'Faiz Ali Rosyadi', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-014', 'Zaimul Himam', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-015', 'Habiburrohman', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-016', 'M. Refan Hanafi', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-017', 'Ahmad Fikri Naufal', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-018', 'Gusti Laxmana Adil', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-019', 'M. Ali Wajdi', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-020', 'Muh. Abdur Rozak', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-021', 'Muhammad Untung Wijaya', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-022', 'Dzihaebi', '', 'Seksi Pendidikan & Penerangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-023', 'M. Bagus Prasetya Budi', '', 'Seksi Wajib Belajar & Murottil (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-024', 'Badrus Sholeh', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-025', 'Faizul Mustaqim', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-026', 'Ahmad Zidni Jal', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-027', 'Ahmad Wafiri', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-028', 'Sa''dulloh Mubarok', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-029', 'M. Azmil Musthofa', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-030', 'Koiman', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-031', 'Khusnul Ma''ab', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-032', 'Akhmad Arya Maulana Sofa', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-033', 'Ahmad Adzim Khaqiqi', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-034', 'Arjun Susanto', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-035', 'Syamsul Arifin', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-036', 'Muhammad Labiebul Chija', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-037', 'M. Zam Zami Maliki', '', 'Seksi Wajib Belajar & Murottil (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-038', 'Ahmad Ihdal Umam', '', 'Seksi Keamanan (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-039', 'Tri Wahyu Kurniawan', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-040', 'Ahmad Rofi''i', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-041', 'M. Ilham Barodi', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-042', 'Saiful Amar', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-043', 'Syauqil Birry', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-044', 'Ahmad Mubarok', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-045', 'Muhammad Fazri', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-046', 'Muhammad Rifki Syamsul Ma''arif', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-047', 'Riki Prasetyo', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-048', 'Ahmad Zahid Eljunaedy', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-049', 'Ikbal Rinaldi', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-050', 'M. Ashar Abdul Malik', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-051', 'M. Shohibul Mighfari', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-052', 'Rizqi Syahru Romadhoni', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-053', 'Moh Zuhan Ahsanul Khuluq', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-054', 'M. Nuruddin', '', 'Seksi Keamanan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-055', 'Nur Hadi', '', 'Seksi Jam''iyyah (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-056', 'Alwan Arbangi', '', 'Seksi Jam''iyyah (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-057', 'Muh. Ali Marwan Hanan', '', 'Seksi Jam''iyyah (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-058', 'Muhammad Isnanto', '', 'Seksi Keuangan (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-059', 'M. Iman Aminulloh', '', 'Seksi Keuangan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-060', 'M. Arsy', '', 'Seksi PLP (Penerangan Listrik Pondok/Pengairan) (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-061', 'Muhammmmad Syahroni', '', 'Seksi PLP (Penerangan Listrik Pondok/Pengairan) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-062', 'Zakiya Fahmi Idris', '', 'Seksi PLP (Penerangan Listrik Pondok/Pengairan) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-063', 'M. Azka Muwafiq', '', 'Seksi Humasy & Logistik (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-064', 'Sayyidun Najib', '', 'Seksi Humasy & Logistik (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-065', 'Sigit Irawan', '', 'Seksi Humasy & Logistik (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-066', 'Dwiki Arifian', '', 'Seksi Humasy & Logistik (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-067', 'Alfa Salim', '', 'Seksi Kebersihan (KBR) (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-068', 'Umar Said', '', 'Seksi Kebersihan (KBR) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-069', 'Moh. Ali Fahmi', '', 'Seksi Kebersihan (KBR) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-070', 'Muhammad Ghufron', '', 'Seksi Kebersihan (KBR) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-071', 'Muhammad Thohir Ubaidillah', '', 'Ketua Blok (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-072', 'Apriyansyah Putra', '', 'Ketua Blok (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-073', 'Fatah Ali Basya', '', 'Ketua Blok (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-074', 'Nur Alif Hidayatul F.', '', 'Seksi Pembangunan (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-075', 'M. Kharfi', '', 'Seksi Pembangunan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-076', 'Moh. Firdaus', '', 'Seksi Pembangunan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-077', 'M. Latif Husain', '', 'Seksi Pembangunan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-078', 'Ahmad Zamzami', '', 'Seksi Dokumentasi & Media Pondok (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-079', 'Ahmad Fauzi', '', 'Seksi Dokumentasi & Media Pondok (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-080', 'Rama Wijaya', '', 'Seksi Dokumentasi & Media Pondok (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-081', 'Allim Mazin', '', 'Seksi Dokumentasi & Media Pondok (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-082', 'A. Nur Ali Sahid', '', 'Takmir Masjid DS B (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-083', 'Syaiful Amri', '', 'Takmir Masjid DS B (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-084', 'Adi Kurniawan', '', 'Takmir Masjid DS B (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-085', 'Khoirullisan', '', 'Takmir Masjid DS B (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-086', 'M. Taufiq Safari', '', 'Takmir Masjid DS C (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-087', 'Muh. Faqih An-naoufal', '', 'Takmir Masjid DS C (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-088', 'M. Abu Sammah Syazani', '', 'Takmir Masjid DS C (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-089', 'Teges Kuncoro', '', 'Takmir Masjid DS C (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-090', 'M. Mafatihul Huda', '', 'Seksi Kesehatan (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-091', 'As''ad Assidiqi', '', 'Seksi Kesehatan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-092', 'M. An''im Falahuddin', '', 'Seksi Kesehatan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-093', 'M. Nur Iqbal Maulana', '', 'Seksi Kesehatan (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-094', 'Malzumul Ilmi', '', 'Seksi BUMP (Badan Usaha Milik Pesantren) (Ketua Seksi)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-095', 'Khoirun Nangim', '', 'Seksi BUMP (Badan Usaha Milik Pesantren) (Anggota)', 'Aktif', 'L');
INSERT INTO ustadz (nik, name, phone, jabatan, status, gender) VALUES ('PGR-096', 'M. Abdullah R.', '', 'Seksi BUMP (Badan Usaha Milik Pesantren) (Anggota)', 'Aktif', 'L');
